# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pump.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(621, 264)
        GroupBox.setTitle("")
        self.groupBox = QtWidgets.QGroupBox(GroupBox)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 461, 121))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(82, 10, 161, 103))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.pulseSpin = QtWidgets.QSpinBox(self.layoutWidget)
        self.pulseSpin.setMaximum(500)
        self.pulseSpin.setSingleStep(50)
        self.pulseSpin.setObjectName("pulseSpin")
        self.gridLayout_2.addWidget(self.pulseSpin, 0, 1, 1, 1)
        self.sourceSet = QtWidgets.QPushButton(self.layoutWidget)
        self.sourceSet.setObjectName("sourceSet")
        self.gridLayout_2.addWidget(self.sourceSet, 3, 1, 1, 1)
        self.frequencySpin = QtWidgets.QSpinBox(self.layoutWidget)
        self.frequencySpin.setMaximum(500)
        self.frequencySpin.setSingleStep(50)
        self.frequencySpin.setObjectName("frequencySpin")
        self.gridLayout_2.addWidget(self.frequencySpin, 1, 1, 1, 1)
        self.currentSpin = QtWidgets.QSpinBox(self.layoutWidget)
        self.currentSpin.setMaximum(500)
        self.currentSpin.setSingleStep(50)
        self.currentSpin.setObjectName("currentSpin")
        self.gridLayout_2.addWidget(self.currentSpin, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(1, 11, 77, 54))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sourceOpen = QtWidgets.QPushButton(self.layoutWidget1)
        self.sourceOpen.setObjectName("sourceOpen")
        self.verticalLayout.addWidget(self.sourceOpen)
        self.sourceClose = QtWidgets.QPushButton(self.layoutWidget1)
        self.sourceClose.setObjectName("sourceClose")
        self.verticalLayout.addWidget(self.sourceClose)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(250, 10, 181, 77))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.firstpumpSpin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.firstpumpSpin.setMaximum(500)
        self.firstpumpSpin.setSingleStep(50)
        self.firstpumpSpin.setObjectName("firstpumpSpin")
        self.gridLayout.addWidget(self.firstpumpSpin, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.secondpumpSpin = QtWidgets.QSpinBox(self.layoutWidget2)
        self.secondpumpSpin.setMaximum(500)
        self.secondpumpSpin.setSingleStep(50)
        self.secondpumpSpin.setObjectName("secondpumpSpin")
        self.gridLayout.addWidget(self.secondpumpSpin, 1, 1, 1, 1)
        self.firstPumpSet = QtWidgets.QPushButton(self.layoutWidget2)
        self.firstPumpSet.setObjectName("firstPumpSet")
        self.gridLayout.addWidget(self.firstPumpSet, 2, 0, 1, 1)
        self.secondPumpSet = QtWidgets.QPushButton(self.layoutWidget2)
        self.secondPumpSet.setObjectName("secondPumpSet")
        self.gridLayout.addWidget(self.secondPumpSet, 2, 1, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.groupBox.setTitle(_translate("GroupBox", "GroupBox"))
        self.label_3.setText(_translate("GroupBox", "设置电流："))
        self.label_2.setText(_translate("GroupBox", "设置频率："))
        self.pulseSpin.setSuffix(_translate("GroupBox", "ms"))
        self.sourceSet.setText(_translate("GroupBox", "种子源设置"))
        self.frequencySpin.setSuffix(_translate("GroupBox", "kHz"))
        self.currentSpin.setSuffix(_translate("GroupBox", "mA"))
        self.label.setText(_translate("GroupBox", "设置脉宽："))
        self.sourceOpen.setText(_translate("GroupBox", "打开平台"))
        self.sourceClose.setText(_translate("GroupBox", "关闭平台"))
        self.label_4.setText(_translate("GroupBox", "一级泵电流："))
        self.firstpumpSpin.setSuffix(_translate("GroupBox", "mA"))
        self.label_5.setText(_translate("GroupBox", "二级泵电流："))
        self.secondpumpSpin.setSuffix(_translate("GroupBox", "mA"))
        self.firstPumpSet.setText(_translate("GroupBox", "一级电流设置"))
        self.secondPumpSet.setText(_translate("GroupBox", "二级电流设置"))

