# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pump.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(549, 214)
        GroupBox.setTitle("")
        self.widget = QtWidgets.QWidget(GroupBox)
        self.widget.setGeometry(QtCore.QRect(0, 0, 450, 200))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sourceOpen = QtWidgets.QPushButton(self.widget)
        self.sourceOpen.setObjectName("sourceOpen")
        self.gridLayout.addWidget(self.sourceOpen, 0, 0, 1, 1)
        self.sourceClose = QtWidgets.QPushButton(self.widget)
        self.sourceClose.setObjectName("sourceClose")
        self.gridLayout.addWidget(self.sourceClose, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.pulseSpin = QtWidgets.QSpinBox(self.widget)
        self.pulseSpin.setMaximum(500)
        self.pulseSpin.setSingleStep(50)
        self.pulseSpin.setObjectName("pulseSpin")
        self.gridLayout_2.addWidget(self.pulseSpin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.frequencySpin = QtWidgets.QSpinBox(self.widget)
        self.frequencySpin.setMaximum(500)
        self.frequencySpin.setSingleStep(50)
        self.frequencySpin.setObjectName("frequencySpin")
        self.gridLayout_2.addWidget(self.frequencySpin, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.currentSpin = QtWidgets.QSpinBox(self.widget)
        self.currentSpin.setMaximum(500)
        self.currentSpin.setSingleStep(50)
        self.currentSpin.setObjectName("currentSpin")
        self.gridLayout_2.addWidget(self.currentSpin, 2, 1, 1, 1)
        self.sourceSet = QtWidgets.QPushButton(self.widget)
        self.sourceSet.setObjectName("sourceSet")
        self.gridLayout_2.addWidget(self.sourceSet, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.firstpumpSpin = QtWidgets.QSpinBox(self.widget)
        self.firstpumpSpin.setMaximum(500)
        self.firstpumpSpin.setSingleStep(50)
        self.firstpumpSpin.setObjectName("firstpumpSpin")
        self.gridLayout_3.addWidget(self.firstpumpSpin, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.secondpumpSpin = QtWidgets.QSpinBox(self.widget)
        self.secondpumpSpin.setMaximum(500)
        self.secondpumpSpin.setSingleStep(50)
        self.secondpumpSpin.setObjectName("secondpumpSpin")
        self.gridLayout_3.addWidget(self.secondpumpSpin, 1, 1, 1, 1)
        self.firstPumpSet = QtWidgets.QPushButton(self.widget)
        self.firstPumpSet.setObjectName("firstPumpSet")
        self.gridLayout_3.addWidget(self.firstPumpSet, 2, 0, 1, 1)
        self.secondPumpSet = QtWidgets.QPushButton(self.widget)
        self.secondPumpSet.setObjectName("secondPumpSet")
        self.gridLayout_3.addWidget(self.secondPumpSet, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.sourceOpen.setText(_translate("GroupBox", "打开平台"))
        self.sourceClose.setText(_translate("GroupBox", "关闭平台"))
        self.label.setText(_translate("GroupBox", "设置脉宽："))
        self.pulseSpin.setSuffix(_translate("GroupBox", "ms"))
        self.label_2.setText(_translate("GroupBox", "设置频率："))
        self.frequencySpin.setSuffix(_translate("GroupBox", "kHz"))
        self.label_3.setText(_translate("GroupBox", "设置电流："))
        self.currentSpin.setSuffix(_translate("GroupBox", "mA"))
        self.sourceSet.setText(_translate("GroupBox", "种子源设置"))
        self.label_4.setText(_translate("GroupBox", "一级泵电流："))
        self.firstpumpSpin.setSuffix(_translate("GroupBox", "mA"))
        self.label_5.setText(_translate("GroupBox", "二级泵电流："))
        self.secondpumpSpin.setSuffix(_translate("GroupBox", "mA"))
        self.firstPumpSet.setText(_translate("GroupBox", "一级电流设置"))
        self.secondPumpSet.setText(_translate("GroupBox", "二级电流设置"))

