# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(492, 242)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 12, 201, 126))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.labelDate = QtWidgets.QLabel(self.widget)
        self.labelDate.setObjectName("labelDate")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelDate)
        self.lineEditDate = QtWidgets.QLineEdit(self.widget)
        self.lineEditDate.setObjectName("lineEditDate")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditDate)
        self.labelWorker = QtWidgets.QLabel(self.widget)
        self.labelWorker.setObjectName("labelWorker")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelWorker)
        self.lineEditWorker = QtWidgets.QLineEdit(self.widget)
        self.lineEditWorker.setObjectName("lineEditWorker")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditWorker)
        self.labelFibertype = QtWidgets.QLabel(self.widget)
        self.labelFibertype.setObjectName("labelFibertype")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelFibertype)
        self.lineEditFibertype = QtWidgets.QLineEdit(self.widget)
        self.lineEditFibertype.setObjectName("lineEditFibertype")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditFibertype)
        self.labelProducer = QtWidgets.QLabel(self.widget)
        self.labelProducer.setObjectName("labelProducer")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelProducer)
        self.lineEditProducer = QtWidgets.QLineEdit(self.widget)
        self.lineEditProducer.setObjectName("lineEditProducer")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditProducer)
        self.labelFiberNo = QtWidgets.QLabel(self.widget)
        self.labelFiberNo.setObjectName("labelFiberNo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelFiberNo)
        self.lineEditFiberNo = QtWidgets.QLineEdit(self.widget)
        self.lineEditFiberNo.setObjectName("lineEditFiberNo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditFiberNo)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(240, 10, 225, 204))
        self.widget1.setObjectName("widget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelTemperature = QtWidgets.QLabel(self.widget1)
        self.labelTemperature.setObjectName("labelTemperature")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelTemperature)
        self.lineEditTemperature = QtWidgets.QLineEdit(self.widget1)
        self.lineEditTemperature.setObjectName("lineEditTemperature")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditTemperature)
        self.labelHumidity = QtWidgets.QLabel(self.widget1)
        self.labelHumidity.setObjectName("labelHumidity")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelHumidity)
        self.lineEditHumidity = QtWidgets.QLineEdit(self.widget1)
        self.lineEditHumidity.setObjectName("lineEditHumidity")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditHumidity)
        self.labelSignalwavelength = QtWidgets.QLabel(self.widget1)
        self.labelSignalwavelength.setObjectName("labelSignalwavelength")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSignalwavelength)
        self.lineEditSignalwavelength = QtWidgets.QLineEdit(self.widget1)
        self.lineEditSignalwavelength.setObjectName("lineEditSignalwavelength")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditSignalwavelength)
        self.labelSingalpulsewidth = QtWidgets.QLabel(self.widget1)
        self.labelSingalpulsewidth.setObjectName("labelSingalpulsewidth")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelSingalpulsewidth)
        self.lineEditSignalpulsewidth = QtWidgets.QLineEdit(self.widget1)
        self.lineEditSignalpulsewidth.setObjectName("lineEditSignalpulsewidth")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditSignalpulsewidth)
        self.labelSingalfrequence = QtWidgets.QLabel(self.widget1)
        self.labelSingalfrequence.setObjectName("labelSignalfrequence")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelSingalfrequence)
        self.lineEditSignalfrequence = QtWidgets.QLineEdit(self.widget1)
        self.lineEditSignalfrequence.setObjectName("lineEditSignalfrequence")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditSignalfrequence)
        self.labelSecondpulsepower = QtWidgets.QLabel(self.widget1)
        self.labelSecondpulsepower.setObjectName("labelSecondpulsepower")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelSecondpulsepower)
        self.lineEditSecondpulsepower = QtWidgets.QLineEdit(self.widget1)
        self.lineEditSecondpulsepower.setObjectName("lineEditSecondpulsepower")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEditSecondpulsepower)
        self.labelFiberlength = QtWidgets.QLabel(self.widget1)
        self.labelFiberlength.setObjectName("labelFiberlength")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelFiberlength)
        self.lineEditFiberlength = QtWidgets.QLineEdit(self.widget1)
        self.lineEditFiberlength.setObjectName("lineEditFiberlength")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEditFiberlength)
        self.labelTimelong = QtWidgets.QLabel(self.widget1)
        self.labelTimelong.setObjectName("labelTimelong")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelTimelong)
        self.lineEditTimelong = QtWidgets.QLineEdit(self.widget1)
        self.lineEditTimelong.setObjectName("lineEditTimelong")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineEditTimelong)
        self.lineEditWorker.raise_()
        self.labelWorker.raise_()
        self.labelDate.raise_()
        self.labelFibertype.raise_()
        self.labelProducer.raise_()
        self.labelFiberNo.raise_()
        self.labelTemperature.raise_()
        self.labelHumidity.raise_()
        self.labelSignalwavelength.raise_()
        self.labelSingalpulsewidth.raise_()
        self.labelSingalfrequence.raise_()
        self.labelSecondpulsepower.raise_()
        self.labelFiberlength.raise_()
        self.labelTimelong.raise_()
        self.lineEditDate.raise_()
        self.lineEditFibertype.raise_()
        self.lineEditProducer.raise_()
        self.lineEditFiberNo.raise_()
        self.lineEditTemperature.raise_()
        self.lineEditHumidity.raise_()
        self.lineEditSignalpulsewidth.raise_()
        self.lineEditSignalfrequence.raise_()
        self.lineEditSecondpulsepower.raise_()
        self.lineEditFiberlength.raise_()
        self.lineEditTimelong.raise_()
        self.labelTemperature.raise_()
        self.lineEditSignalwavelength.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelDate.setText(_translate("Dialog", "日期："))
        self.labelWorker.setText(_translate("Dialog", "操作人："))
        self.labelFibertype.setText(_translate("Dialog", "光纤型号："))
        self.labelProducer.setText(_translate("Dialog", "生产厂家："))
        self.labelFiberNo.setText(_translate("Dialog", "光纤编号："))
        self.labelTemperature.setText(_translate("Dialog", "环境温度："))
        self.labelHumidity.setText(_translate("Dialog", "环境湿度："))
        self.labelSignalwavelength.setText(_translate("Dialog", "信号光波长："))
        self.labelSingalpulsewidth.setText(_translate("Dialog", "信号光脉宽："))
        self.labelSingalfrequence.setText(_translate("Dialog", "信号光频率："))
        self.labelSecondpulsepower.setText(_translate("Dialog", "二级泵浦功率："))
        self.labelFiberlength.setText(_translate("Dialog", "光纤长度："))
        self.labelTimelong.setText(_translate("Dialog", "测试时长："))

